spring.application.name=4-22retry
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/beauty_db
spring.datasource.username=postgres
spring.datasource.password=postgres
